package com.vlessclient.model;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class ServerConfigTest {

    private final ObjectMapper mapper = new ObjectMapper();

    @Test
    void jacksonRoundTrip_preservesAllFields() throws Exception {
        ServerConfig original = new ServerConfig();
        original.setName("My Server");
        original.setProtocol(Protocol.VLESS);
        original.setAddress("10.0.0.1");
        original.setPort(443);
        original.setUuid("11111111-2222-3333-4444-555555555555");
        original.setEncryption("none");
        original.setFlow("xtls-rprx-vision");
        original.setActive(true);

        original.getTransport().setType(TransportType.WEBSOCKET);
        original.getTransport().setPath("/ws");
        original.getTransport().setHost("cdn.example.com");
        original.getTransport().getHeaders().put("Host", "cdn.example.com");

        original.getTls().setEnabled(true);
        original.getTls().setServerName("example.com");
        original.getTls().setAlpn("h2");
        original.getTls().setFingerprint("chrome");
        original.getTls().setAllowInsecure(false);
        original.getTls().setReality(true);
        original.getTls().setRealityPublicKey("pubkey123");
        original.getTls().setRealityShortId("ab01");

        String json = mapper.writeValueAsString(original);
        ServerConfig deserialized = mapper.readValue(json, ServerConfig.class);

        assertThat(deserialized.getId()).isEqualTo(original.getId());
        assertThat(deserialized.getName()).isEqualTo("My Server");
        assertThat(deserialized.getProtocol()).isEqualTo(Protocol.VLESS);
        assertThat(deserialized.getAddress()).isEqualTo("10.0.0.1");
        assertThat(deserialized.getPort()).isEqualTo(443);
        assertThat(deserialized.getUuid()).isEqualTo("11111111-2222-3333-4444-555555555555");
        assertThat(deserialized.getEncryption()).isEqualTo("none");
        assertThat(deserialized.getFlow()).isEqualTo("xtls-rprx-vision");
        assertThat(deserialized.isActive()).isTrue();

        assertThat(deserialized.getTransport().getType()).isEqualTo(TransportType.WEBSOCKET);
        assertThat(deserialized.getTransport().getPath()).isEqualTo("/ws");
        assertThat(deserialized.getTransport().getHost()).isEqualTo("cdn.example.com");
        assertThat(deserialized.getTransport().getHeaders()).containsEntry("Host", "cdn.example.com");

        assertThat(deserialized.getTls().isEnabled()).isTrue();
        assertThat(deserialized.getTls().getServerName()).isEqualTo("example.com");
        assertThat(deserialized.getTls().getAlpn()).isEqualTo("h2");
        assertThat(deserialized.getTls().getFingerprint()).isEqualTo("chrome");
        assertThat(deserialized.getTls().isAllowInsecure()).isFalse();
        assertThat(deserialized.getTls().isReality()).isTrue();
        assertThat(deserialized.getTls().getRealityPublicKey()).isEqualTo("pubkey123");
        assertThat(deserialized.getTls().getRealityShortId()).isEqualTo("ab01");
    }

    @Test
    void defaultValues_setCorrectly() {
        ServerConfig config = new ServerConfig();

        assertThat(config.getEncryption()).isEqualTo("none");
        assertThat(config.isActive()).isFalse();
        assertThat(config.getFlow()).isNull();
        assertThat(config.getTransport()).isNotNull();
        assertThat(config.getTransport().getType()).isEqualTo(TransportType.TCP);
        assertThat(config.getTransport().getHeaders()).isNotNull().isEmpty();
        assertThat(config.getTls()).isNotNull();
        assertThat(config.getTls().isEnabled()).isFalse();
        assertThat(config.getTls().isReality()).isFalse();
        assertThat(config.getTls().isAllowInsecure()).isFalse();
    }

    @Test
    void idAutoGenerated_asUuid() {
        ServerConfig config = new ServerConfig();

        assertThat(config.getId()).isNotNull();
        assertThat(config.getId()).isNotEmpty();

        // Verify it parses as a valid UUID
        java.util.UUID parsed = java.util.UUID.fromString(config.getId());
        assertThat(parsed.toString()).isEqualTo(config.getId());
    }

    @Test
    void twoInstances_haveDifferentIds() {
        ServerConfig a = new ServerConfig();
        ServerConfig b = new ServerConfig();

        assertThat(a.getId()).isNotEqualTo(b.getId());
    }

    @Test
    void deserializationWithUnknownFields_ignored() throws Exception {
        String json = """
                {
                  "id": "test-id",
                  "name": "Test",
                  "protocol": "vless",
                  "address": "1.2.3.4",
                  "port": 443,
                  "uuid": "some-uuid",
                  "unknown_field": "should be ignored"
                }
                """;

        ServerConfig config = mapper.readValue(json, ServerConfig.class);

        assertThat(config.getId()).isEqualTo("test-id");
        assertThat(config.getName()).isEqualTo("Test");
        assertThat(config.getProtocol()).isEqualTo(Protocol.VLESS);
    }
}
