#!/usr/bin/env bash
#
# Desktop-VM Linux QA in a Lima VM (no admin rights needed on the host):
# exercises the three things the container harness (linux-qa.sh) cannot —
#
#   C. system tray on a real XEmbed tray host (trayer under Xvfb)
#   A. GNOME system-proxy set/restore round-trip (gsettings + dbus session)
#   B. TUN interface creation AND teardown through the app's setcap fast path
#
# The TUN teardown check is the one that caught the orphaned-core /
# leaked-tunnel bug (PR #67): after the app is stopped, both sing-box and
# utun99 must be gone.
#
# Usage:  scripts/linux-vm-qa.sh          # creates/reuses the 'vless-qa' VM
#         scripts/linux-vm-qa.sh --delete # remove the VM afterwards
#
# The guest builds the CURRENT COMMIT (the repo is mounted read-only and
# cloned inside), so commit before running. Artifacts land in
# target/linux-vm-qa/: tray screenshot, gsettings trace, ip-link dumps, logs.
#
# Requires: brew install lima   (VM boots Ubuntu LTS, arm64 on Apple Silicon)
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${REPO_ROOT}/target/linux-vm-qa"
VM=vless-qa
BRANCH="$(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD)"

command -v limactl >/dev/null || { echo "[vm-qa] lima is required: brew install lima" >&2; exit 1; }
mkdir -p "${OUT_DIR}"

if ! limactl list --format '{{.Name}}' 2>/dev/null | grep -qx "${VM}"; then
    echo "[vm-qa] creating VM ${VM} (first boot downloads the Ubuntu image)"
    limactl create --name="${VM}" --cpus=4 --memory=8 --disk=30 \
        --vm-type=vz --tty=false template://ubuntu-lts
fi
if [ "$(limactl list --format '{{.Status}}' "${VM}" 2>/dev/null)" != "Running" ]; then
    limactl start "${VM}" --tty=false
fi

GUEST_SCRIPT=$(mktemp)
trap 'rm -f "${GUEST_SCRIPT}"' EXIT
{
  echo '#!/bin/bash'
  echo '# Runs inside the Lima guest. Generated by scripts/linux-vm-qa.sh.'
  echo 'set -uo pipefail'
  echo "REPO=${REPO_ROOT}"
  echo "QA_BRANCH=${BRANCH}"
  cat <<'GUEST_EOF'
WORK=$HOME/vless-qa
OUT=$WORK/out
DATA=$HOME/.local/share/vless-client
rm -rf "$WORK" "$DATA"
mkdir -p "$OUT"

echo "=== provision ==="
sudo apt-get update -q >/dev/null
sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  wget apt-transport-https gpg git maven xvfb xauth imagemagick x11-apps x11-utils \
  trayer dbus-x11 gsettings-desktop-schemas libglib2.0-bin procps psmisc \
  libgtk-3-0t64 libglib2.0-0t64 libxtst6 libxi6 libxrender1 libxrandr2 \
  libfreetype6 fontconfig libasound2t64 libgl1 libpango-1.0-0 libcairo2 \
  fonts-dejavu-core libcap2-bin iproute2 >/dev/null 2>&1
if ! command -v java >/dev/null 2>&1 || ! java -version 2>&1 | grep -q '"25'; then
  wget -qO- https://packages.adoptium.net/artifactory/api/gpg/key/public \
    | sudo gpg --dearmor --yes -o /usr/share/keyrings/adoptium.gpg
  echo "deb [signed-by=/usr/share/keyrings/adoptium.gpg] https://packages.adoptium.net/artifactory/deb $(. /etc/os-release && echo "$VERSION_CODENAME") main" \
    | sudo tee /etc/apt/sources.list.d/adoptium.list >/dev/null
  sudo apt-get update -q >/dev/null
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq temurin-25-jdk >/dev/null 2>&1
fi
java -version 2>&1 | head -1

echo "=== build ($QA_BRANCH) ==="
git clone -q -b "$QA_BRANCH" "$REPO" "$WORK/repo" && cd "$WORK/repo"
git log --oneline -1
mvn -B -q clean package -DskipTests < /dev/null 2>&1 | tail -2 || true
JAR=$(ls target/vless-client-*.jar | head -1)
echo "jar: $JAR"

# Fixtures: one dummy active server; health checks off to keep logs quiet.
# Only the JSON files are rewritten — bin/ keeps the extracted core and its
# setcap grant across phases. proxy_mode is the lowercase enum value.
fixtures() { # $1 = proxy mode (system_proxy | tun)
  rm -f "$DATA"/servers.json "$DATA"/settings.json "$DATA"/subscriptions.json
  mkdir -p "$DATA"
  cat > "$DATA/servers.json" <<EOF
{ "config_version": 1, "servers": [ {
  "id": "qa-1", "name": "qa-dummy", "protocol": "vless",
  "address": "192.0.2.10", "port": 443,
  "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6", "active": true } ] }
EOF
  cat > "$DATA/settings.json" <<EOF
{ "config_version": 1, "auto_connect": true, "proxy_mode": "$1",
  "system_proxy_auto_config": true, "health_check_enabled": false,
  "store_secrets_securely": false }
EOF
}

# Mirrors the packaged launcher's options (package-linux.sh): without
# -Djava.awt.headless=false AWT goes headless and the tray silently dies.
APP_OPTS="-Dprism.order=sw -Djava.awt.headless=false"

echo "=== phase C: tray on a real tray host ==="
fixtures system_proxy
xvfb-run -a -s "-screen 0 1280x800x24" bash -c '
  trayer --edge top --align right --width 10 --height 24 &
  TRAYER=$!
  sleep 2
  java '"$APP_OPTS"' -jar '"$JAR"' > '"$OUT"'/tray-app.log 2>&1 &
  APP=$!
  sleep 25
  import -window root '"$OUT"'/tray-screenshot.png
  kill -TERM $APP 2>/dev/null; sleep 3; kill -9 $APP $TRAYER 2>/dev/null
'
if grep -q "tray is not supported" "$OUT/tray-app.log"; then
  echo "TRAY: NOT SUPPORTED (unexpected with trayer present)"
else
  echo "TRAY: no 'not supported' warning — icon path exercised"
fi

echo "=== phase A: GNOME proxy set/restore ==="
fixtures system_proxy
dbus-run-session -- bash -c '
  gsettings set org.gnome.system.proxy mode "none"
  echo "before: $(gsettings get org.gnome.system.proxy mode)" > '"$OUT"'/proxy-trace.txt
  xvfb-run -a -s "-screen 0 1280x800x24" bash -c "
    java '"$APP_OPTS"' -jar '"$JAR"' > '"$OUT"'/proxy-app.log 2>&1 &
    APP=\$!
    sleep 30
    echo \"during: \$(gsettings get org.gnome.system.proxy mode)\" >> '"$OUT"'/proxy-trace.txt
    echo \"host:   \$(gsettings get org.gnome.system.proxy.http host)\" >> '"$OUT"'/proxy-trace.txt
    kill -TERM \$APP 2>/dev/null
    for i in \$(seq 1 20); do kill -0 \$APP 2>/dev/null || break; sleep 0.5; done
    echo \"after:  \$(gsettings get org.gnome.system.proxy mode)\" >> '"$OUT"'/proxy-trace.txt
  "
'
cat "$OUT/proxy-trace.txt"

echo "=== phase B: TUN device up AND teardown (setcap fast path) ==="
CORE=$(find "$DATA" -name sing-box -type f 2>/dev/null | head -1)
echo "core: $CORE"
sudo setcap cap_net_admin+ep "$CORE" && getcap "$CORE"
fixtures tun
xvfb-run -a -s "-screen 0 1280x800x24" bash -c '
  java '"$APP_OPTS"' -jar '"$JAR"' > '"$OUT"'/tun-app.log 2>&1 &
  APP=$!
  for i in $(seq 1 30); do ip link | grep -q utun99 && break; sleep 1; done
  ip link > '"$OUT"'/iplink-during.txt
  kill -TERM $APP 2>/dev/null
  for i in $(seq 1 20); do kill -0 $APP 2>/dev/null || break; sleep 0.5; done
  kill -9 $APP 2>/dev/null
'
# Teardown is asynchronous (signal → wrapper → core exit → kernel cleanup):
# poll up to 30s before calling it a leak.
for i in $(seq 1 30); do ip link | grep -q utun99 || break; sleep 1; done
ip link > "$OUT/iplink-after.txt"
if grep -q utun99 "$OUT/iplink-during.txt"; then echo "TUN up:       utun99 PRESENT while connected"; else echo "TUN up:       utun99 MISSING (unexpected)"; fi
if grep -q utun99 "$OUT/iplink-after.txt"; then echo "TUN teardown: STILL PRESENT 30s after stop (LEAK)"; else echo "TUN teardown: removed after stop (OK)"; fi
if pgrep -x sing-box >/dev/null; then echo "core teardown: sing-box STILL RUNNING (LEAK)"; pkill -9 sing-box; else echo "core teardown: sing-box gone (OK)"; fi
echo "=== VM QA DONE ==="
GUEST_EOF
} > "${GUEST_SCRIPT}"

echo "[vm-qa] running the guest scenario (first run provisions JDK + Maven cache)"
limactl cp "${GUEST_SCRIPT}" "${VM}:vm-qa-generated.sh"
limactl shell "${VM}" -- bash "/home/${USER}.linux/vm-qa-generated.sh" 2>/dev/null \
  || limactl shell "${VM}" -- bash vm-qa-generated.sh

echo "[vm-qa] collecting artifacts"
limactl shell "${VM}" -- bash -c 'cd ~/vless-qa/out 2>/dev/null && tar cf - .' 2>/dev/null \
  | tar xf - -C "${OUT_DIR}" 2>/dev/null || true
ls -la "${OUT_DIR}" 2>/dev/null || true

if [ "${1:-}" = "--delete" ]; then
    limactl stop "${VM}" || true
    limactl delete "${VM}"
    echo "[vm-qa] VM deleted"
fi